# Generated by Django 5.0.3 on 2024-05-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_kind_alter_account_name_accountreport'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_cents', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('kind', models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Investment'), (3, 'Transfer')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('account_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountreport')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category')),
            ],
        ),
    ]
