# Generated by Django 5.0.3 on 2024-04-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('borrowed_value_cents', models.IntegerField()),
                ('parcels', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financings',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary', models.BooleanField(default=True)),
                ('parcel', models.IntegerField()),
                ('paid_parcels', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('amortization_cents', models.IntegerField()),
                ('interest_cents', models.IntegerField()),
                ('insurance_cents', models.IntegerField()),
                ('fees_cents', models.IntegerField()),
                ('monetary_correction_cents', models.IntegerField()),
                ('adjustment_cents', models.IntegerField()),
                ('financing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='users.financing')),
            ],
            options={
                'verbose_name_plural': 'Installments',
            },
        ),
        migrations.CreateModel(
            name='Transference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cents', models.IntegerField()),
                ('date', models.DateField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='account.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
