# Generated by Django 5.0.3 on 2024-04-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_financing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financing',
            old_name='installments',
            new_name='parcels',
        ),
    ]
