# Generated by Django 5.0.3 on 2024-04-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_installments_financing_parcels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary', models.BooleanField(default=True)),
                ('parcel', models.IntegerField()),
                ('paid_parcels', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('amortization_cents', models.IntegerField()),
                ('interest_cents', models.IntegerField()),
                ('insurance_cents', models.IntegerField()),
                ('fees_cents', models.IntegerField()),
                ('monetary_correction_cents', models.IntegerField()),
                ('adjustment_cents', models.IntegerField()),
                ('financing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.financing')),
            ],
            options={
                'verbose_name_plural': 'Installments',
            },
        ),
    ]
