# Generated by Django 5.0.3 on 2024-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_cents',
            field=models.IntegerField(default=0),
        ),
    ]
